apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rc-name
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: tmp-name
      labels:
        env: dev
    spec:
      containers:
        - name: c1
          image: nginx
          ports:
            - containerPort: 80
